services:
  app:
    build: ./api
    container_name: api_container
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    command: ["npm", "run", "dev"]

  blog:
    build: ./myblog
    container_name: blog_container_client
    ports:
      - "3000:3000"
    volumes:
      - ./myblog:/app
      - /app/node_modules
    command: ["npm", "start"]